import { StyleSheet } from 'react-native';

export const stylePokedex = StyleSheet.create({
  wrapper: {
    width: '100%',
    alignItems: 'center',
  },
  shell: {
    width: '100%',
    borderRadius: 34,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
    backgroundColor: '#EE4F49',
    shadowColor: '#8F2321',
    shadowOffset: {
      width: 0,
      height: 16,
    },
    shadowOpacity: 0.28,
    shadowRadius: 22,
    elevation: 10,
  },
  topBar: {
    minHeight: 64,
    paddingHorizontal: 10,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  camera: {
    position: 'absolute',
    top: -3,
    left: '50%',
    marginLeft: -36,
    width: 72,
    height: 28,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    backgroundColor: '#D93A3F',
  },
  leftIndicators: {
    flexDirection: 'column',
    gap: 6,
  },
  leftIndicator: {
    width: 34,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#E9FFF9',
    opacity: 0.95,
  },
  rightIndicator: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#6EE7E6',
    borderWidth: 3,
    borderColor: 'rgba(207,255,254,0.85)',
  },
  screen: {
    overflow: 'hidden',
    borderRadius: 22,
    paddingHorizontal: 10,
    paddingTop: 28,
    paddingBottom: 10,
    backgroundColor: '#35C6C8',
  },
  screenLineLeft: {
    position: 'absolute',
    left: 18,
    top: 18,
    width: '32%',
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(220,255,247,0.8)',
  },
  screenLineRight: {
    position: 'absolute',
    right: 18,
    top: 18,
    width: '32%',
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(220,255,247,0.8)',
  },
  arrow: {
    alignSelf: 'center',
    width: 0,
    height: 0,
    marginBottom: 18,
    borderLeftWidth: 26,
    borderRightWidth: 26,
    borderBottomWidth: 16,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'rgba(183, 255, 234, 0.92)',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  emptyText: {
    textAlign: 'center',
    color: '#0F586B',
    fontWeight: '700',
    paddingVertical: 20,
  },
});
