import { StyleSheet } from 'react-native';

export const styleDetailPokemon = StyleSheet.create({
  card: {
    borderRadius: 20,
    backgroundColor: '#F8F0DF',
    borderWidth: 4,
    borderColor: '#6AB764',
    overflow: 'hidden',
    shadowColor: '#7E1E1E',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 8,
  },
  heroPanel: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#F8F0DF',
  },
  title: {
    fontSize: 34,
    fontWeight: '900',
    color: '#1A1714',
    textTransform: 'uppercase',
  },
  divider: {
    marginTop: 10,
    marginBottom: 12,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#5D3B1D',
  },
  artworkFrame: {
    minHeight: 360,
    borderWidth: 4,
    borderColor: '#6AB764',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAF5EA',
    padding: 8,
  },
  artwork: {
    width: '100%',
    height: 330,
  },
  artworkPlaceholder: {
    width: '100%',
    height: 330,
    borderRadius: 8,
    backgroundColor: '#E7DBC6',
  },
  bottomGrid: {
    flexDirection: 'row',
    gap: 10,
    padding: 10,
    backgroundColor: '#F0E2C9',
  },
  infoPanel: {
    flex: 1.4,
    minHeight: 170,
    borderWidth: 3,
    borderColor: '#7A5A2D',
    backgroundColor: '#F8F0DF',
    padding: 12,
  },
  notesPanel: {
    flex: 1,
    minHeight: 170,
    borderWidth: 3,
    borderColor: '#7A5A2D',
    backgroundColor: '#F8F0DF',
    padding: 10,
    justifyContent: 'space-between',
  },
  genus: {
    fontSize: 19,
    fontWeight: '800',
    color: '#1D1A16',
  },
  metaRow: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  metaId: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1D1A16',
  },
  typeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  typeBadge: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  typeBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  measurements: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: '800',
    color: '#1D1A16',
    lineHeight: 26,
  },
  thumbRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: 10,
  },
  thumbFrame: {
    width: 82,
    height: 82,
    borderWidth: 2,
    borderColor: '#6AB764',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF9EE',
  },
  thumbImage: {
    width: 64,
    height: 64,
  },
  flavorText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#51453B',
    textAlign: 'center',
    fontWeight: '700',
  },
});
