import { StyleSheet } from 'react-native';

export const styleAuthForm = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
    backgroundColor: '#F7E4BF',
  },
  shell: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    borderRadius: 30,
    padding: 18,
    backgroundColor: '#E84C44',
    shadowColor: '#8F2321',
    shadowOffset: {
      width: 0,
      height: 16,
    },
    shadowOpacity: 0.24,
    shadowRadius: 22,
    elevation: 10,
  },
  topDecor: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingHorizontal: 8,
  },
  camera: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#63D7E8',
    borderWidth: 4,
    borderColor: '#D8FBFF',
  },
  indicatorRow: {
    flexDirection: 'row',
    gap: 8,
  },
  indicator: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFE07D',
  },
  card: {
    borderRadius: 24,
    padding: 22,
    backgroundColor: '#FFF6E7',
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#976B19',
  },
  title: {
    marginTop: 8,
    fontSize: 32,
    fontWeight: '900',
    color: '#1D1A16',
  },
  subtitle: {
    marginTop: 8,
    marginBottom: 18,
    fontSize: 15,
    lineHeight: 22,
    color: '#5F5449',
    fontWeight: '600',
  },
  error: {
    marginBottom: 14,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#FCE2E2',
    color: '#A62D2D',
    fontSize: 13,
    fontWeight: '700',
  },
  fieldGroup: {
    marginBottom: 14,
  },
  label: {
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '800',
    color: '#4E4338',
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 2,
    borderColor: '#E6D4B5',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    fontSize: 15,
    color: '#1D1A16',
    shadowColor: '#D5B788',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  helper: {
    marginTop: 4,
    marginBottom: 18,
    fontSize: 12,
    color: '#7B6E60',
    fontWeight: '600',
  },
  button: {
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    backgroundColor: '#2D72C8',
    shadowColor: '#1D4D88',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.26,
    shadowRadius: 14,
    elevation: 6,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
});
